# Generated by Django 3.1.5 on 2021-01-17 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='content',
        ),
    ]
