# Generated by Django 3.1.5 on 2021-01-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='body',
        ),
    ]
