# Generated by Django 3.1.5 on 2021-01-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_auto_20210117_0427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='photo',
            new_name='main_photo',
        ),
    ]
