# Generated by Django 3.1.5 on 2021-01-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0007_auto_20210118_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='detail_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='detail_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='detail_photo_3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
